// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBj7OSRomtrvuy2hVFo3PPSV18a3muLrQ8',
    appId: '1:747249749147:web:ec4b28549108ffa5d28a3e',
    messagingSenderId: '747249749147',
    projectId: 'live-stream-6648a',
    authDomain: 'live-stream-6648a.firebaseapp.com',
    storageBucket: 'live-stream-6648a.appspot.com',
    measurementId: 'G-8SW1DHYZ51',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBAnWMgoTHRyriIWWxZiF6tqS3lh_A4zAI',
    appId: '1:747249749147:android:239d7c125f259b50d28a3e',
    messagingSenderId: '747249749147',
    projectId: 'live-stream-6648a',
    storageBucket: 'live-stream-6648a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAKT3AnsJTyYHrwLyKrE2UrL4uwymqMfrQ',
    appId: '1:747249749147:ios:d2fb41ca961083e7d28a3e',
    messagingSenderId: '747249749147',
    projectId: 'live-stream-6648a',
    storageBucket: 'live-stream-6648a.appspot.com',
    iosBundleId: 'com.example.flutterEmail',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAKT3AnsJTyYHrwLyKrE2UrL4uwymqMfrQ',
    appId: '1:747249749147:ios:d2fb41ca961083e7d28a3e',
    messagingSenderId: '747249749147',
    projectId: 'live-stream-6648a',
    storageBucket: 'live-stream-6648a.appspot.com',
    iosBundleId: 'com.example.flutterEmail',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBj7OSRomtrvuy2hVFo3PPSV18a3muLrQ8',
    appId: '1:747249749147:web:588562e247c46c83d28a3e',
    messagingSenderId: '747249749147',
    projectId: 'live-stream-6648a',
    authDomain: 'live-stream-6648a.firebaseapp.com',
    storageBucket: 'live-stream-6648a.appspot.com',
    measurementId: 'G-LZ6XTT7DBC',
  );
}
